gremlin:instrumental_package.h instrumental_package.cpp Robot.h Robot.cpp Controler.h Controler.cpp main.cpp
	g++ instrumental_package.h instrumental_package.cpp Robot.h Robot.cpp Controler.h Controler.cpp main.cpp -o TheGremlin -std=c++11
run:
	./TheGremlin
clean:
	rm TheGremlin
